In [1]:
import numpy as np

p_data = open("/Users/joshem/PhD Research/Data/cora/cora.cites")


# Create a list from the data
myls=list(p_data)

# Remove the new line symbole from the list
mylist = [line.rstrip('\n') for line in myls]
#print(mylist)
#print(graph_ind)
#print(graph_level)

p_data.close()

In [25]:
print(mylist)

['35\t1033', '35\t103482', '35\t103515', '35\t1050679', '35\t1103960', '35\t1103985', '35\t1109199', '35\t1112911', '35\t1113438', '35\t1113831', '35\t1114331', '35\t1117476', '35\t1119505', '35\t1119708', '35\t1120431', '35\t1123756', '35\t1125386', '35\t1127430', '35\t1127913', '35\t1128204', '35\t1128227', '35\t1128314', '35\t1128453', '35\t1128945', '35\t1128959', '35\t1128985', '35\t1129018', '35\t1129027', '35\t1129573', '35\t1129683', '35\t1129778', '35\t1130847', '35\t1130856', '35\t1131116', '35\t1131360', '35\t1131557', '35\t1131752', '35\t1133196', '35\t1133338', '35\t1136814', '35\t1137466', '35\t1152421', '35\t1152508', '35\t1153065', '35\t1153280', '35\t1153577', '35\t1153853', '35\t1153943', '35\t1154176', '35\t1154459', '35\t116552', '35\t12576', '35\t128540', '35\t132806', '35\t135130', '35\t141342', '35\t141347', '35\t148170', '35\t15670', '35\t1688', '35\t175291', '35\t178727', '35\t18582', '35\t190697', '35\t190706', '35\t1956', '35\t197054', '35\t198443', '35\t1986

In [30]:
mynode=[]
Edgelist=[]
i=0
for d in mylist:
    d=mylist[i].split("\t")
    mynode.append(int(d[0]))
    mynode.append(int(d[1]))
    Edgelist.append([int(d[0]),int(d[1])])
    i=i+1
#print(mynode)
node_ID1=np.unique(mynode)
node_ID=list(node_ID1)
print(node_ID)
n=len(node_ID)
print(n)

[35, 40, 114, 117, 128, 130, 164, 288, 424, 434, 463, 504, 506, 887, 906, 910, 936, 940, 941, 943, 1026, 1033, 1034, 1035, 1213, 1237, 1246, 1272, 1365, 1385, 1481, 1688, 1694, 1717, 1786, 1817, 1919, 1949, 1951, 1952, 1953, 1955, 1956, 1959, 1997, 1999, 2354, 2440, 2653, 2654, 2658, 2663, 2665, 2695, 2696, 2698, 2702, 3084, 3085, 3095, 3097, 3101, 3112, 3187, 3191, 3192, 3217, 3218, 3220, 3222, 3223, 3229, 3231, 3232, 3233, 3235, 3236, 3237, 3240, 3243, 3828, 3932, 4274, 4329, 4330, 4335, 4553, 4584, 4637, 4649, 4660, 4804, 4878, 4983, 5038, 5055, 5062, 5064, 5069, 5075, 5086, 5194, 5348, 5454, 5462, 5600, 5869, 5959, 5966, 6125, 6130, 6151, 6152, 6155, 6163, 6169, 6170, 6184, 6196, 6209, 6210, 6213, 6214, 6215, 6216, 6217, 6220, 6224, 6238, 6311, 6318, 6334, 6343, 6344, 6346, 6378, 6385, 6539, 6639, 6741, 6767, 6771, 6775, 6782, 6784, 6786, 6814, 6818, 6898, 6910, 6913, 6917, 6923, 6925, 6935, 6939, 6941, 7022, 7032, 7041, 7047, 7272, 7276, 7296, 7297, 7419, 7430, 7432, 7532, 7537, 7

In [32]:
print(Edgelist)

[[35, 1033], [35, 103482], [35, 103515], [35, 1050679], [35, 1103960], [35, 1103985], [35, 1109199], [35, 1112911], [35, 1113438], [35, 1113831], [35, 1114331], [35, 1117476], [35, 1119505], [35, 1119708], [35, 1120431], [35, 1123756], [35, 1125386], [35, 1127430], [35, 1127913], [35, 1128204], [35, 1128227], [35, 1128314], [35, 1128453], [35, 1128945], [35, 1128959], [35, 1128985], [35, 1129018], [35, 1129027], [35, 1129573], [35, 1129683], [35, 1129778], [35, 1130847], [35, 1130856], [35, 1131116], [35, 1131360], [35, 1131557], [35, 1131752], [35, 1133196], [35, 1133338], [35, 1136814], [35, 1137466], [35, 1152421], [35, 1152508], [35, 1153065], [35, 1153280], [35, 1153577], [35, 1153853], [35, 1153943], [35, 1154176], [35, 1154459], [35, 116552], [35, 12576], [35, 128540], [35, 132806], [35, 135130], [35, 141342], [35, 141347], [35, 148170], [35, 15670], [35, 1688], [35, 175291], [35, 178727], [35, 18582], [35, 190697], [35, 190706], [35, 1956], [35, 197054], [35, 198443], [35, 1986

In [99]:

edgelist=[]
i=0
for d in mylist:
    d=mylist[i].split("\t")
    edgelist.append([node_ID.index(int(d[0])),node_ID.index(int(d[1]))])
    i=i+1
print(edgelist)

[[0, 21], [0, 905], [0, 906], [0, 1909], [0, 1940], [0, 1943], [0, 2059], [0, 2117], [0, 2122], [0, 2131], [0, 2143], [0, 2195], [0, 2229], [0, 2233], [0, 2248], [0, 2292], [0, 2301], [0, 2324], [0, 2336], [0, 2340], [0, 2342], [0, 2346], [0, 2353], [0, 2366], [0, 2368], [0, 2374], [0, 2378], [0, 2380], [0, 2396], [0, 2401], [0, 2402], [0, 2426], [0, 2427], [0, 2433], [0, 2469], [0, 2479], [0, 2492], [0, 2524], [0, 2525], [0, 2570], [0, 2572], [0, 2606], [0, 2610], [0, 2639], [0, 2655], [0, 2657], [0, 2666], [0, 2681], [0, 2695], [0, 2702], [0, 950], [0, 240], [0, 997], [0, 1010], [0, 1028], [0, 1053], [0, 1054], [0, 1073], [0, 281], [0, 31], [0, 1135], [0, 1144], [0, 311], [0, 1173], [0, 1175], [0, 42], [0, 1196], [0, 1199], [0, 1200], [0, 1212], [0, 1217], [0, 1250], [0, 1255], [0, 1287], [0, 1290], [0, 1298], [0, 1304], [0, 1305], [0, 1314], [0, 1317], [0, 1321], [0, 1329], [0, 399], [0, 422], [0, 1341], [0, 1344], [0, 445], [0, 1348], [0, 1349], [0, 1350], [0, 1366], [0, 1393], [0,

In [3]:
A=np.zeros((n,n))
i=0
for d in mylist:
    d=mylist[i].split("\t")
    A[node_ID.index(int(d[0]))][node_ID.index(int(d[1]))]=1
    i=i+1;
print(" The adjacency Matrix")
print("=======================")
print(A)

 The adjacency Matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
import os
data_dir = os.path.expanduser("/Users/joshem/PhD Research/Data/cora")
import pandas as pd
feature_names = ["w_{}".format(ii) for ii in range(1433)]
column_names = ["ID"]+ feature_names + ["subject"]
node_data = pd.read_csv(os.path.join(data_dir, "cora.content"), sep='\t', header=None, names=column_names)
node_data.head()

ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_1424  w_1425  \
0    31336    0    0    0    0    0    0    0    0    0  ...       0       0   
1  1061127    0    0    0    0    0    0    0    0    0  ...       0       1   
2  1106406    0    0    0    0    0    0    0    0    0  ...       0       0   
3    13195    0    0    0    0    0    0    0    0    0  ...       0       0   
4    37879    0    0    0    0    0    0    0    0    0  ...       0       0   

   w_1426  w_1427  w_1428  w_1429  w_1430  w_1431  w_1432  \
0       1       0       0       0       0       0       0   
1       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0   

                  subject  
0         Neural_Networks  
1           Rule_Learning  
2  Reinforcement_Learning  
3  Reinforcement_Learning  
4   Probabilistic_Methods  

[5 rows x 1435 columns]

In [5]:
DataS=node_data.replace({'subject': {'Case_Based':0 , 'Genetic_Algorithms': 1,'Neural_Networks':2,'Probabilistic_Methods':3 , 'Reinforcement_Learning': 4,'Rule_Learning':5,'Theory':6}})
# Case_Based==0
#		Genetic_Algorithms==1
#		Neural_Networks==2
#		Probabilistic_Methods==3
#		Reinforcement_Learning==4
#		Rule_Learning==5
#		Theory==6
DataS.head()

ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_1424  w_1425  \
0    31336    0    0    0    0    0    0    0    0    0  ...       0       0   
1  1061127    0    0    0    0    0    0    0    0    0  ...       0       1   
2  1106406    0    0    0    0    0    0    0    0    0  ...       0       0   
3    13195    0    0    0    0    0    0    0    0    0  ...       0       0   
4    37879    0    0    0    0    0    0    0    0    0  ...       0       0   

   w_1426  w_1427  w_1428  w_1429  w_1430  w_1431  w_1432  subject  
0       1       0       0       0       0       0       0        2  
1       0       0       0       0       0       0       0        5  
2       0       0       0       0       0       0       0        4  
3       0       0       0       0       0       0       0        4  
4       0       0       0       0       0       0       0        3  

[5 rows x 1435 columns]

In [6]:
Data=DataS.sort_values(by=['ID'],ascending=True)
Data.head()

ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_1424  w_1425  \
163    35    0    0    0    0    0    0    0    0    0  ...       0       0   
168    40    0    0    0    0    0    0    0    0    0  ...       0       0   
552   114    0    0    0    0    0    0    0    1    0  ...       0       0   
1459  117    0    0    0    0    0    0    0    0    0  ...       0       0   
554   128    0    1    0    0    0    0    0    0    0  ...       0       0   

      w_1426  w_1427  w_1428  w_1429  w_1430  w_1431  w_1432  subject  
163        0       0       0       0       0       0       0        1  
168        0       0       0       0       0       0       0        1  
552        0       0       0       0       0       0       0        4  
1459       0       0       0       0       0       0       0        4  
554        0       0       0       0       0       0       0        4  

[5 rows x 1435 columns]

In [7]:
catagories=Data['subject'].to_numpy()
print(catagories)
import random
p=random.sample(range(2708), 1000)
#print(p)
q=[]
for i in range(n):
    if i not in p:
        q.append(i)
#print(q)

[1 1 4 ... 5 5 5]


In [8]:
class_60=np.array(catagories)
for d in p:
    class_60[d]=7
print(class_60)
for i in range(n):
    A[i][i]=class_60[i]
print(A)

[1 7 4 ... 7 5 5]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 7. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 7. 0. 0.]
 [0. 0. 0. ... 0. 5. 0.]
 [0. 0. 0. ... 0. 0. 5.]]


In [9]:
Node_class=[0,1,2,3,4,5,6,7]
F_vec=[]
for i in range(n):
    node_F=[]
    list_out=[]
    list_In=[]
    S_nbd_out=[]
    S_nbd_in=[]
    for j in range(n):
        if A[i][j]==1 and i!=j:
            list_out.append(A[j][j])
            for k in range(n):
                if A[j][k]==1 and k!=j:
                    S_nbd_out.append(A[k][k])
        if A[j][i]==1 and i!=j:
            list_In.append(A[j][j])
            for k in range(n):
                if A[k][j]==1 and k!=j:
                    S_nbd_in.append(A[k][k])
                
    for d in Node_class:
        count=0
        count_in=0
        for k in range(len(list_out)):
            if list_out[k]==d:
                count=count+1
        node_F.append(count)
        for k in range(len(list_In)):
            if list_In[k]==d:
                count_in=count_in+1
        node_F.append(count_in)
    for d in Node_class:
        count_S_out=0
        count_S_in=0
        for k in range(len(S_nbd_out)):
            if S_nbd_out[k]==d:
                count_S_out=count_S_out+1
        node_F.append(count_S_out)
        for k in range(len(S_nbd_in)):
            if S_nbd_in[k]==d:
                count_S_in=count_S_in+1
        node_F.append(count_S_in)
    F_vec.append(node_F)

In [10]:
x =np.array(F_vec)
k=32
data=pd.DataFrame({"a_0":x[:,0]})
data.insert(loc=1, column="b_0", value=x[:,1])
for i in range(1,k-1,2):
    data.insert(loc=i+1, column="a_{}".format(int((i+1)/2)), value=x[:,i+1])
    data.insert(loc=i+2, column="b_{}".format(int((i+1)/2)), value=x[:,i+2])

data.insert(loc=k,column='Class',value=Data['subject'].to_numpy())
data.head()

a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  ...  b_11  a_12  b_12  \
0    1    0  102    2    4    0    0    0    3    0  ...     0    14     0   
1    0    0    3    1    0    0    0    0    0    0  ...     0     0     0   
2    0    0    0    0    0    0    1    0   24    0  ...     0    32     0   
3    0    0    0    0    0    0    2    0    9    0  ...     0    23     0   
4    0    0    0    0    0    0    0    0    4    2  ...     0     2     1   

   a_13  b_13  a_14  b_14  a_15  b_15  Class  
0     3     0     4     0   148     2      1  
1     0     0     0     0     1     0      1  
2     0     0     1     0    24     0      4  
3     0     0     0     0    24     0      4  
4     0     0     0     0     2     1      4  

[5 rows x 33 columns]

In [12]:
!pip install XGBoost

  Obtaining dependency information for XGBoost from https://files.pythonhosted.org/packages/13/94/f73d4efcc9a0272ea9f93c03f4744a2b709172309cd0bfde1e9012776330/xgboost-2.0.1-py3-none-macosx_12_0_arm64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 9.2 MB/s eta 0:00:00a 0:00:01


In [13]:
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))

X=data[feature] # Features
y=data['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1)
bst.fit(X_train,y_train)
y_pred=bst.predict(X_test)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")

Accuracy: 82.8 %


In [14]:
class_60=np.array(catagories)
i=0
for d in p:
    class_60[d]=y_pred[i]
    i=i+1
#print(class_60)
for i in range(n):
    A[i][i]=class_60[i]
#print(A)
Node_class=[0,1,2,3,4,5,6]
F_vec=[]
for i in range(n):
    node_F=[]
    list_out=[]
    list_In=[]
    S_nbd_out=[]
    S_nbd_in=[]
    for j in range(n):
        if A[i][j]==1 and i!=j:
            list_out.append(A[j][j])
            for k in range(n):
                if A[j][k]==1 and k!=j:
                    S_nbd_out.append(A[k][k])
        if A[j][i]==1 and i!=j:
            list_In.append(A[j][j])
            for k in range(n):
                if A[k][j]==1 and k!=j:
                    S_nbd_in.append(A[k][k])
                
    for d in Node_class:
        count=0
        count_in=0
        for k in range(len(list_out)):
            if list_out[k]==d:
                count=count+1
        node_F.append(count)
        for k in range(len(list_In)):
            if list_In[k]==d:
                count_in=count_in+1
        node_F.append(count_in)
    for d in Node_class:
        count_S_out=0
        count_S_in=0
        for k in range(len(S_nbd_out)):
            if S_nbd_out[k]==d:
                count_S_out=count_S_out+1
        node_F.append(count_S_out)
        for k in range(len(S_nbd_in)):
            if S_nbd_in[k]==d:
                count_S_in=count_S_in+1
        node_F.append(count_S_in)
    F_vec.append(node_F)
x =np.array(F_vec)
k=28
data=pd.DataFrame({"a_0":x[:,0]})
data.insert(loc=1, column="b_0", value=x[:,1])
for i in range(1,k-1,2):
    data.insert(loc=i+1, column="a_{}".format(int((i+1)/2)), value=x[:,i+1])
    data.insert(loc=i+2, column="b_{}".format(int((i+1)/2)), value=x[:,i+2])

data.head(30)


a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  ...  a_9  b_9  a_10  \
0     1    0  155    3    5    0    0    0    4    0  ...   11    1     0   
1     0    0    3    1    0    0    0    0    0    0  ...    0    0     0   
2     0    0    0    0    1    0    1    0   40    0  ...    4    0     0   
3     0    0    0    0    0    0    3    0   14    0  ...    1    0     3   
4     0    0    0    0    0    1    0    0    4    3  ...    1    1     0   
5     0    0    0    0    0    0    0    1    3    3  ...    0    0     0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0     0   
7     0    0    0    0    1    0    0    0    1    0  ...    0    0     0   
8     2    0    0    0    1    1    0    1    0    0  ...    0    2     0   
9     0    0    0    0    1    0    0    0    0    2  ...    0    1     0   
10    1    0    0    0    0    0    0    0    0    0  ...    0    0     0   
11    0    0    0    0    0    0    4    0    0    0  ...    0    0     8   
12    0    0    0    0    0    0    3    2    0    0  ...    0    0     5   
13    3    0   11    3    1    0    0    0   11    0  ...    5    1     0   
14    0    0    0    0    7    0    0    0    0    0  ...   37    0     2   
15    0    0    1    0   36    4    2    1    2    0  ...   24    5     2   
16    8    0    0    0    0    0    0    0    0    0  ...    0    0     0   
17    3    1    0    0    0    0    0    0    0    0  ...    0    0     0   
18    5    0    0    0    0    0    0    0    0    0  ...    0    0     0   
19    3    2    0    0    0    0    0    0    0    0  ...    0    0     0   
20    0    0    5    0    0    0    0    0    0    0  ...    0    0     0   
21    0    0    2    3    0    0    0    0    0    0  ...    0    1     0   
22    0    0    1    2    0    0    0    0    0    1  ...    0    0     0   
23    0    0    3    1    0    0    0    0    0    1  ...    0    1     0   
24    0    0    0    0    0    0    0    0    0    0  ...    0    0     0   
25    0    0    0    0    2    0    0    0    1    0  ...    2    0     0   
26    0    0    0    0    0    0    0    0    0    0  ...    0    0     0   
27    4    0    2    0    4    2    0    0    2    0  ...    5    2     0   
28    0    0    1    0   65    0    1    0    6    0  ...   47    0     5   
29    0    0    0    0    0    1    0    0    0    3  ...    0    5     0   

    b_10  a_11  b_11  a_12  b_12  a_13  b_13  
0      0    24     0     4     0     7     0  
1      0     0     0     0     0     0     0  
2      0    54     0     0     0     1     0  
3      0    44     0     0     0     0     0  
4      0     3     1     0     0     0     0  
5      1     1     8     0     0     0     0  
6      0     0     0     0     0     0    12  
7      0     0     0     0     0     0     1  
8      1     0     0     0     0     0     0  
9      0     0     1     0     3     0     0  
10     0     0     0     0     0     0     0  
11     0     0     0     0     0     0     0  
12     2     0     0     0     0     0     0  
13     0    96     0     3     0     6     0  
14     0     2     0     0     0     0     0  
15     0     1     0     0     0     2     0  
16     0     0     0     4     0     0     0  
17     0     0     0     0     0     0     0  
18     0     0     0     0     0     0     0  
19     0     0     0     0     0     0     0  
20     0     0     0     0     0     0     0  
21     0     0     0     0     0     0     0  
22     0     0     1     0     0     0     0  
23     0     0     0     0     0     0     0  
24     0     0     0     1     0     0     0  
25     0     0     0     0     0     0     0  
26     0     0     0     0     0     7     0  
27     1     0     1    15     0    11     0  
28     0     5     0     2     0     1     0  
29     1     0     7     0     0     0     0  

[30 rows x 28 columns]

In [15]:
Data_0=Data.loc[Data['subject'] == 0]
Data_1=Data.loc[Data['subject'] == 1]
Data_2=Data.loc[Data['subject'] == 2]
Data_3=Data.loc[Data['subject'] == 3]
Data_4=Data.loc[Data['subject'] == 4]
Data_5=Data.loc[Data['subject'] == 5]
Data_6=Data.loc[Data['subject'] == 6]

In [16]:
Basis_0=[]
Basis_1=[]
Basis_2=[]
Basis_3=[]
Basis_4=[]
Basis_5=[]
Basis_6=[]
for i in range(1433):
    W="w_{}".format(i)
    Basis_0.append(max(Data_0[W].to_numpy()))
    Basis_1.append(max(Data_1[W].to_numpy()))
    Basis_2.append(max(Data_2[W].to_numpy()))
    Basis_3.append(max(Data_3[W].to_numpy()))
    Basis_4.append(max(Data_4[W].to_numpy()))
    Basis_5.append(max(Data_5[W].to_numpy()))
    Basis_6.append(max(Data_6[W].to_numpy()))
#W1=Data_0['w_0'].to_numpy()
#print(max(W1))
count0=0
count1=0
for i in range(1433):
    if Basis_0[i]==1:
        count1=count1+1
    else:
        count0=count0+1
print(count0)
print(count1)

537
896


In [17]:
SBasis_0=[]
SBasis_1=[]
SBasis_2=[]
SBasis_3=[]
SBasis_4=[]
SBasis_5=[]
SBasis_6=[]
#for i in range(14):
 #   W="w_{}".format(i)
  #  print(list(Data_0[W].to_numpy()).count(1))
for i in range(1433):
    W="w_{}".format(i)
    if list(Data_0[W].to_numpy()).count(1)>=int(len(Data_0.index)*0.1):
        SBasis_0.append(1)
    else:
        SBasis_0.append(0) 
    if list(Data_1[W].to_numpy()).count(1)>=int(len(Data_1.index)*0.1):
        SBasis_1.append(1)
    else:
        SBasis_1.append(0)
    if list(Data_2[W].to_numpy()).count(1)>=int(len(Data_2.index)*0.1):
        SBasis_2.append(1)
    else:
        SBasis_2.append(0)
    if list(Data_3[W].to_numpy()).count(1)>=int(len(Data_3.index)*0.1):
        SBasis_3.append(1)
    else:
        SBasis_3.append(0)
    if list(Data_4[W].to_numpy()).count(1)>=int(len(Data_4.index)*0.1):
        SBasis_4.append(1)
    else:
        SBasis_4.append(0)
    if list(Data_5[W].to_numpy()).count(1)>=int(len(Data_5.index)*0.1):
        SBasis_5.append(1)
    else:
        SBasis_5.append(0)
    if list(Data_6[W].to_numpy()).count(1)>=int(len(Data_6.index)*0.1):
        SBasis_6.append(1)
    else:
        SBasis_6.append(0)
#W1=Data_0['w_0'].to_numpy()
#print(max(W1))
count0=0
count1=0
for i in range(1433):
    if SBasis_0[i]==1:
        count1=count1+1
    else:
        count0=count0+1
print(count0)
print(count1)

1405
28


In [18]:
IdS=list(DataS['ID'].to_numpy())
Id=list(Data['ID'].to_numpy())
#print(Id)
#print(IdS)
print(IdS.index(Id[1]))

168


In [19]:
Fec=[]
for i in range(2708):
    vec=[]
    f=Data.loc[IdS.index(Id[i]), feature_names].values.flatten().tolist()
    count=0
    count1=0
    count2=0
    count3=0
    count4=0
    count5=0
    count6=0
    for j in range(1433):
        if f[j]==1 and Basis_0[j]==1:
            count=count+1;
        if f[j]==1 and Basis_1[j]==1:
            count1=count1+1;
        if f[j]==1 and Basis_2[j]==1:
            count2=count2+1;
        if f[j]==1 and Basis_3[j]==1:
            count3=count3+1;
        if f[j]==1 and Basis_4[j]==1:
            count4=count4+1;
        if f[j]==1 and Basis_5[j]==1:
            count5=count5+1;
        if f[j]==1 and Basis_6[j]==1:
            count6=count6+1;
    vec.append(count)
    vec.append(count1)
    vec.append(count2)
    vec.append(count3)
    vec.append(count4)
    vec.append(count5)
    vec.append(count6)
    #print(f)
    f.clear()
    Fec.append(vec)

In [20]:
SFec=[]
for i in range(2708):
    Svec=[]
    f=Data.loc[IdS.index(Id[i]), feature_names].values.flatten().tolist()
    count=0
    count1=0
    count2=0
    count3=0
    count4=0
    count5=0
    count6=0
    for j in range(1433):
        if f[j]==1 and SBasis_0[j]==1:
            count=count+1;
        if f[j]==1 and SBasis_1[j]==1:
            count1=count1+1;
        if f[j]==1 and SBasis_2[j]==1:
            count2=count2+1;
        if f[j]==1 and SBasis_3[j]==1:
            count3=count3+1;
        if f[j]==1 and SBasis_4[j]==1:
            count4=count4+1;
        if f[j]==1 and SBasis_5[j]==1:
            count5=count5+1;
        if f[j]==1 and SBasis_6[j]==1:
            count6=count6+1;
    Svec.append(count)
    Svec.append(count1)
    Svec.append(count2)
    Svec.append(count3)
    Svec.append(count4)
    Svec.append(count5)
    Svec.append(count6)
    #print(f)
    f.clear()
    SFec.append(Svec)
print(SFec)

[[1, 7, 3, 2, 3, 2, 1], [6, 5, 3, 4, 6, 7, 4], [1, 3, 1, 1, 4, 3, 1], [5, 4, 4, 4, 8, 2, 5], [5, 3, 3, 2, 8, 2, 3], [6, 6, 5, 5, 10, 3, 5], [3, 2, 2, 1, 3, 1, 4], [4, 4, 4, 4, 7, 5, 5], [4, 3, 4, 3, 3, 4, 3], [3, 3, 2, 2, 2, 3, 4], [6, 5, 2, 3, 4, 5, 5], [1, 0, 0, 1, 0, 2, 1], [2, 1, 0, 1, 0, 1, 0], [2, 1, 1, 1, 1, 2, 3], [0, 3, 3, 1, 3, 0, 1], [3, 4, 4, 4, 4, 4, 4], [5, 3, 2, 2, 3, 3, 1], [4, 2, 3, 2, 6, 2, 4], [7, 3, 2, 2, 4, 4, 3], [9, 2, 3, 2, 4, 4, 3], [2, 4, 2, 3, 2, 2, 2], [4, 7, 4, 3, 5, 3, 3], [4, 6, 4, 3, 4, 3, 3], [2, 4, 2, 2, 4, 1, 3], [3, 3, 1, 1, 2, 7, 3], [2, 2, 2, 1, 2, 2, 1], [3, 3, 2, 2, 3, 3, 2], [1, 0, 0, 0, 1, 3, 4], [1, 2, 2, 3, 2, 2, 3], [1, 2, 2, 2, 4, 1, 2], [6, 3, 2, 1, 3, 2, 1], [4, 4, 3, 2, 2, 2, 2], [4, 4, 4, 3, 4, 2, 2], [2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1], [3, 7, 3, 3, 5, 4, 5], [2, 2, 2, 2, 4, 2, 0], [12, 5, 3, 2, 6, 6, 3], [2, 1, 0, 0, 1, 0, 0], [10, 5, 4, 4, 5, 5, 4], [4, 3, 3, 2, 3, 2, 2], [5, 1, 1, 1, 1, 4, 3], [5, 3, 4, 2, 4, 5, 2], [6, 2, 

In [21]:
z =np.array(SFec)
data2=pd.DataFrame({"S_0":z[:,0]})
for i in range(6):
    data2.insert(loc=i+1, column="S_{}".format(i+1), value=z[:,i+1])
#data2.insert(loc=7,column='Class',value=Data['subject'].to_numpy())
data2.head()

S_0  S_1  S_2  S_3  S_4  S_5  S_6
0    1    7    3    2    3    2    1
1    6    5    3    4    6    7    4
2    1    3    1    1    4    3    1
3    5    4    4    4    8    2    5
4    5    3    3    2    8    2    3

In [22]:
y =np.array(Fec)
data1=pd.DataFrame({"In_0":y[:,0]})
for i in range(6):
    data1.insert(loc=i+1, column="In_{}".format(i+1), value=y[:,i+1])
data1.insert(loc=7,column='Class',value=Data['subject'].to_numpy())
data1.head()

In_0  In_1  In_2  In_3  In_4  In_5  In_6  Class
0    16    20    20    16    17    12    14      1
1    16    18    18    17    15    16    15      1
2    10    11    12    10    12     7     8      4
3    13    17    19    18    20    14    18      4
4    17    17    19    17    20    15    17      4

In [23]:
result = pd.concat([data,data2,data1], axis=1)
result.head()

a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  ...  S_5  S_6  In_0  \
0    1    0  155    3    5    0    0    0    4    0  ...    2    1    16   
1    0    0    3    1    0    0    0    0    0    0  ...    7    4    16   
2    0    0    0    0    1    0    1    0   40    0  ...    3    1    10   
3    0    0    0    0    0    0    3    0   14    0  ...    2    5    13   
4    0    0    0    0    0    1    0    0    4    3  ...    2    3    17   

   In_1  In_2  In_3  In_4  In_5  In_6  Class  
0    20    20    16    17    12    14      1  
1    18    18    17    15    16    15      1  
2    11    12    10    12     7     8      4  
3    17    19    18    20    14    18      4  
4    17    19    17    20    15    17      4  

[5 rows x 43 columns]

In [24]:
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))
for i in range(7):
    feature.append("S_{}".format(i))
for j in range(7):
    feature.append("In_{}".format(j))
#print(feature)
X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]
from xgboost import XGBClassifier
bst = XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1)
bst.fit(X_train,y_train)
y_pred=bst.predict(X_test)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")

Accuracy: 88.1 %


In [37]:
Data=result.drop(['Class'], axis=1)
Data.head()

a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  ...  S_4  S_5  S_6  In_0  \
0    1    0  155    3    5    0    0    0    4    0  ...    3    2    1    16   
1    0    0    3    1    0    0    0    0    0    0  ...    6    7    4    16   
2    0    0    0    0    1    0    1    0   40    0  ...    4    3    1    10   
3    0    0    0    0    0    0    3    0   14    0  ...    8    2    5    13   
4    0    0    0    0    0    1    0    0    4    3  ...    8    2    3    17   

   In_1  In_2  In_3  In_4  In_5  In_6  
0    20    20    16    17    12    14  
1    18    18    17    15    16    15  
2    11    12    10    12     7     8  
3    17    19    18    20    14    18  
4    17    19    17    20    15    17  

[5 rows x 42 columns]

In [133]:
De=Data.to_numpy()
Fe=np.array(De,dtype="f")
print(Fe)

[[  1.   0. 155. ...  17.  12.  14.]
 [  0.   0.   3. ...  15.  16.  15.]
 [  0.   0.   0. ...  12.   7.   8.]
 ...
 [  0.   0.   0. ...  15.  20.  15.]
 [  0.   0.   0. ...  13.  19.  12.]
 [  0.   0.   0. ...  13.  18.  17.]]


In [120]:
Class=result['Class'].to_numpy()
print(Class)

[1 1 4 ... 5 5 5]


In [139]:
train=[]
for j in range(2708):
    if j in q:
        train.append(True)
    else:
        train.append(False)
        j=j+1
        
print(train)

[True, False, True, True, False, False, False, False, False, True, False, True, True, True, True, False, True, True, True, True, True, False, True, True, False, True, False, False, False, False, False, True, False, False, True, True, True, True, True, False, True, True, True, True, True, False, True, True, True, False, True, True, True, True, True, True, False, False, False, True, True, True, True, True, False, True, True, True, True, True, False, True, False, True, True, True, False, True, True, True, False, True, True, False, True, True, False, False, True, True, True, True, False, True, True, False, True, True, False, False, False, False, True, True, False, False, False, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, False, True, False, False, False, True, True, False, True, False, False, True, False, True, True, True, False, False, False, True, False, True, True, False, True, True, True, True, False, False, True, True, True, True, True, T

In [140]:
import torch
edgelist=np.array(edgelist)
x = torch.from_numpy(Fe)
edge_index=torch.from_numpy(edgelist)
y=torch.from_numpy(Class)
train_mask=torch.from_numpy(np.array(train))
print(y)

tensor([1, 1, 4,  ..., 5, 5, 5])


In [53]:
# Helper function for visualization.
%matplotlib inline
import torch
import networkx as nx
import matplotlib.pyplot as plt

# Visualization function for NX graph or PyTorch tensor
def visualize(h, color, epoch=None, loss=None, accuracy=None):
    plt.figure(figsize=(7,7))
    plt.xticks([])
    plt.yticks([])

    if torch.is_tensor(h):
        h = h.detach().cpu().numpy()
        plt.scatter(h[:, 0], h[:, 1], s=140, c=color, cmap="Set2")
        if epoch is not None and loss is not None and accuracy['train'] is not None and accuracy['val'] is not None:
            plt.xlabel((f'Epoch: {epoch}, Loss: {loss.item():.4f} \n'
                       f'Training Accuracy: {accuracy["train"]*100:.2f}% \n'
                       f' Validation Accuracy: {accuracy["val"]*100:.2f}%'),
                       fontsize=16)
    else:
        nx.draw_networkx(G, pos=nx.spring_layout(G, seed=42), with_labels=False,
                         node_color=color, cmap="Set2")
    plt.show()

In [55]:
num_features=len(feature)
print(num_features)

42


In [146]:
#implementing GCN network
import torch
from torch.nn import Linear
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        torch.manual_seed(1234)
        self.conv1 = GCNConv(num_features, 42)
        self.conv2 = GCNConv(42, 42)
        self.conv3 = GCNConv(42, 42)
        self.classifier = Linear(42, 7) #7 class, 2 input

    def forward(self, x, edge_index):
        h = self.conv1(x, edge_index)
        h = h.tanh()
        h = self.conv2(h, edge_index)
        h = h.tanh()
        h = self.conv3(h, edge_index)
        h = h.tanh()  # Final GNN embedding space.

        # Apply a final (linear) classifier.
        out = self.classifier(h)

        return out, h

model = GCN()
print(model)

GCN(
  (conv1): GCNConv(42, 42)
  (conv2): GCNConv(42, 42)
  (conv3): GCNConv(42, 42)
  (classifier): Linear(in_features=42, out_features=7, bias=True)
)


In [136]:
Edge=torch.transpose(edge_index, 0, 1)
x.dtype

torch.float32

In [147]:
import time
#from IPython.display import Javascript  # Restrict height of output cell.
#display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 430})'''))

model = GCN()
criterion = torch.nn.CrossEntropyLoss()  # Define loss criterion.
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)  # Define optimizer.

def train(x, edge_index, train_mask,y):
    optimizer.zero_grad()  # Clear gradients.
    out, h = model(x, edge_index)  # Perform a single forward pass.
    loss = criterion(out[train_mask], y[train_mask])  # Compute the loss solely based on the training nodes.
    loss.backward()  # Derive gradients.
    optimizer.step()  # Update parameters based on gradients.

    accuracy = {}
    # Calculate training accuracy on our four examples
    predicted_classes = torch.argmax(out[train_mask], axis=1) # [0.6, 0.2, 0.7, 0.1] -> 2
    target_classes = y[train_mask]
    accuracy['train'] = torch.mean(
        torch.where(predicted_classes == target_classes, 1, 0).float())

    # Calculate validation accuracy on the whole graph
    predicted_classes = torch.argmax(out, axis=1)
    target_classes = y
    accuracy['val'] = torch.mean(
        torch.where(predicted_classes == target_classes, 1, 0).float())

    return loss, h, accuracy

for epoch in range(500):
    loss, h, accuracy = train(x, Edge,train_mask,y)
    # Visualize the node embeddings every 10 epochs
    if epoch % 10 == 0:
        #visualize(h, color=y, epoch=epoch, loss=loss, accuracy=accuracy)
        #time.sleep(0.3)
        print(f'Epoch: {epoch}, Loss: {loss.item():.4f},Training Accuracy: {accuracy["train"]*100:.2f}% Validation Accuracy: {accuracy["val"]*100:.2f}%')

Epoch: 0, Loss: 1.9448,Training Accuracy: 7.08% Validation Accuracy: 7.13%
Epoch: 10, Loss: 0.6381,Training Accuracy: 82.79% Validation Accuracy: 81.79%
Epoch: 20, Loss: 0.3849,Training Accuracy: 89.81% Validation Accuracy: 87.74%
Epoch: 30, Loss: 0.2998,Training Accuracy: 90.63% Validation Accuracy: 88.77%
Epoch: 40, Loss: 0.2533,Training Accuracy: 91.80% Validation Accuracy: 89.73%
Epoch: 50, Loss: 0.2186,Training Accuracy: 93.15% Validation Accuracy: 90.66%
Epoch: 60, Loss: 0.1930,Training Accuracy: 93.68% Validation Accuracy: 90.95%
Epoch: 70, Loss: 0.1732,Training Accuracy: 94.50% Validation Accuracy: 91.47%
Epoch: 80, Loss: 0.1539,Training Accuracy: 95.43% Validation Accuracy: 91.91%
Epoch: 90, Loss: 0.1354,Training Accuracy: 95.78% Validation Accuracy: 92.13%
Epoch: 100, Loss: 0.1779,Training Accuracy: 93.62% Validation Accuracy: 90.32%
Epoch: 110, Loss: 0.1299,Training Accuracy: 95.78% Validation Accuracy: 92.21%
Epoch: 120, Loss: 0.1140,Training Accuracy: 96.25% Validation Acc

In [72]:
x.size()

torch.Size([2708, 42])

In [73]:
edge_index.size()

torch.Size([5429, 2])

In [ ]:
    print(f'Epoch [{epoch+1}/{num_epochs}] - Loss: {total_loss:.4f}, Train Accuracy: {train_accuracy:.2f}%, Test Accuracy: {test_accuracy:.2f}%')